dist: trusty
sudo: required

language: ruby

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install docker-engine

before_script:
  - mkdir dist
  - docker --version
  - docker-compose up -d --build
  - docker ps -a

script:
  - docker exec starter jest
  - docker exec starter gulp dist

after_success:
  - ls dist

after_script:
  - docker-compose down