version: '2'

services:
  dev:
    container_name: starter
    build: .
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - ./dist:/app/dist
      - /app/node_modules
    command: gulp dev
    
